// SPDX-License-Identifier: EUPL-1.2

import { defineStore } from 'pinia';

export const useMockStore = defineStore('mock', {
  state: () => ({
    getDocuments: {
      request: {
        id: 'string',
        func: 'getDocuments',
        data: {},
      },
      response: {
        id: 'string',
        status: 'SUCCESS',
        data: {
          documents: [
            {
              meta: {
                id: 'wYJMnQeApGnc',
                documentIdentifier: 'eu.europa.ec.eudi.pid.1',
                issuerDisplay: {
                  name: 'Digital Credentials Issuer',
                  issuingCountry: 'LV',
                  issuingAuthority: 'SIA Dativa',
                  logo: {
                    altText: 'EU Digital Identity Wallet Logo',
                  },
                },
                documentDisplay: {
                  name: 'PID',
                  logo: {
                    altText: 'Personas identifikācijas dati',
                  },
                },
                status: 'Issued',
                hasExpired: false,
                isFavorite: true,
                expirationDate: '2025-11-19 00:00',
                issuanceDate: '2025-08-21 00:00',
              },
              documentDetails: [
                {
                  type: 'image',
                  identifier: 'test_img',
                  label: 'Test image',
                  value: 'AAA',
                  image:
                    '_9j_4AAQSkZJRgABAQIAJQAlAAD_4QBiRXhpZgAATU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAMAAAITAAMAAAABAAEAAAAAAAAAAAAlAAAAAQAAACUAAAAB_9sAQwADAgICAgIDAgICAwMDAwQGBAQEBAQIBgYFBgkICgoJCAkJCgwPDAoLDgsJCQ0RDQ4PEBAREAoMEhMSEBMPEBAQ_8AACwgBsQFoAQERAP_EAB4AAQABBAMBAQAAAAAAAAAAAAABAgcICQMEBgoF_8QASRAAAQMDAwMCBQAHBAYGCwAAAQACAwQFEQYHEgghMQlBEyJRYXEUIzJCUoGRFWJyshgzOHWCwhZDobHR8CQlJjQ1REaFs8PU_9oACAEBAAA_ANqL_ZSPClERERERERERERERERERERERERERERUv9vypHhSiIiIiIiIi4Q93_k5I_Psvy7_qiw6Vtk961LfaG1W-mbzmqq2pZTwsbj9oveQGjse5IH3Vir16hnRpYq6S31u_thfNE7DjSRVNXFn7SQxPa4fgrqD1J-iR_wCxvxbj_wDa7gP_ANC_E1f6pPRhpaifUUu51VqCpa3Io7RZqt8z_wAOljZEP-J4Vuz60HS04fq9GbnfztND_wD2LyJ9bDa4ainp27M6pdYW5-BXfp8H6U_s0_NT44M7kj_Wu8L8mq9bvTUdZPHQ9Pd1nphK4QSS6jjje6MeHOYKd3B31bycB7OXYqfW30T-kUYpNi72ad7miqfLeImvYD5MYbE4Px93NVwZ_WQ6WYqlsAse4UzBHHI-aC1Uvw2lzWuMeX1IcXMyWO-XBcxxa4tw53vtLeqP0YanjgbNunPY6mVveC6WesiLHfwue2N0Y_Iesk9F670luLYabVWhtTW--WirGYauhnbLE7_ibnv9shejRERERERERERUv9vypHhSiIiIiIijIX5V6vtu07bKq9Xy501voKCB9TU1NRK2KGGJgy973uOGtaO5JIA8Ela5t5vWY0pp7UE9j2W0B_0opaaV0ZutxqX00VRxdjMUQHMtJ_ZLi0keWrEDfD1N-pzeCpMNs1M3RVoc3j-gWF5j5fd8zsyH-RasbNS7n7k6ypP7P1buHqS90jZPitguN1nqYw_-INkcRnv5XmCSexPhEySMEnAQEjwSnJx8uP8AVTyd_Ef6pyd3-Y9_Pfyge8Yw89vHfwo5O-pVydpuoPenZKsM-1m4d3sTXSfEkpoJS6CQ_V0Tg5hP5C2JdNnrERzPp9MdS1mFO48YxqK0U5c0Euxymp25-UDuXMz_AIXLZbpTWGntb2Ci1TpC_Ul5s9yiZNSV1FM2aCVjs9w9p748HuDkY_aBC_fyFKIiIiIiIiKl_t-VI8KURERERRkfVdK43KitlHLcLhcKekpIGfFlmnlDGMZ_E5xIDR9z2WIPUJ6oPTxs02W1aSvTNf6gAcBTWWpa-lheOwEtSAYwM-zC4_XitPu8PUzvPvdqC63vWuvr1LT3Ob4ptcddIyiiZz5RxthDuBDfqRlWlyfGShJPknsiIiIiIiZP1VTXuJ7uJ8nz9fKvv0zdXe7_AEwaghuGjL1UVFikmDq6xVUhdSVLB-3huPkecftNwR75W7jpv6v9nOp2xCs0BqNkd7hjY64WKsIiraJ3FvLLCf1rORAD4-QPIAlrsht9GOLhnPnwqh4UoiIiIiIipf7flSPClERERFB8K12_m_m33Ttt_Xbg7hXcU9NSjFNSxvBqK6Y_sxRM8kl2AfZoBJ-UFaZOsT1B9fdVdJT6Uo7QNK6UpZnSuoYKovfWOPYGd_ytOG_ugYysRnPz4Kjk7OeRz9cqEREREREREU83YI5HBxkZ8r9vSurNS6HvtLqXSN7rbNdaJwkgq6SZ0U0Z98EHJB75Hus_Omz1dtyNJV9Hp7qApRqqxktjddKSJkdxp2-73BoDJh3OR8rhjsVte2z3R0JvFouh17ttqilvlkr2coqmne5pYWn5mPY4B0cjT-0x7Q4HsQAvYZb9VUiIiIiIipf7flSPClERERF4vdXdLR-zWgLzuVr28C32ayUxnne7HKR2QGRRtP7Ukji1jWeSXADHcrQj1k9WN16rtxo9WSWR1ms1ugNLbaAzukw3k4mR_fjzcCMhoAGBhY85I8EoiIiIiIiIiIiZOMZU8nYI5HBOSMq-nS71abldK-sf7b0VXGostdLH_a1kmcTTVjB5IHlkgGeLx3GRnK3v9P3UJt51Jbe0e4e3V1E8M2I62ieQKi3VAALoZmeWuwcg-HN4ubkOBN0g5rhkFVIiIiIiKl_t-VI8KURERF1pKhkeXukwG-SQcAfnOMDySfZaS_U96vnb27iO2m0TdXS6K0hUPY-SneTDX1wy18vbs5rAXNaT7lx-iwU5HOcnP1RERERERERERERE5H6lXn6Yep3X_S3uFHrjRtQailnaIbpapXEQ3CnySQ7HhwJPF3kZOFvq6c-oHRPUttbQboaFndHT1DjTV1HKQZrfWMDTJBJjsDhzHA-C17XeCALroiIiIiKl_t-VI8KURERFrd9UPreOgbTV9O21l1lh1LdIf_aC4U7-JoqRzDmna7yJXjHI-zPl8uHHT2ZHZJ8E-VSiIiIiIiIiIiIiIp5OHhx_qspegrq6uvSzueyS4zSz6K1G-OmvlKCeMBzgVTR_EweR7sJ_hC36W250d2oKa522qZU0tZEyeGVjgQ-N4Ba4Y7EEEH-a7yIiIiIqX-35UjwpRERF1KqshoKeWsq52xQQsdJJI92A1gBJJz2wACST9F81fUHraPcXfLXWuKOsdWU13vlZUU0_f9ZAJSI3j6Dg1uPsrbIiIiIiIiIiIiIiIiqD3e3t2W5n0jepiu3J23r9kNVVj57toWJklrnleC6W2PPFsZ9_1TsN_wALox4C2GoiIiIipf7flSPClEREWIXqi7nXvbDpJv79P1bqWr1VXU2nDO1-HMhna90wb75dFDI37CRx8gLQq4nx7fRQiIiIiIiIiIiIiIiIskugzqEh6dOoexasulVwsN2YbPeXPGGx00zwBIT7CNwZJgecFfQZSVcVZBHVU0okgmjbJG9juTS0jIcD75BBXaRERERUv9vypHhSiIiLU960u7sNZdNE7JUTnl1vEl-uAz8vKRpjhbjxkN59_wC-tXCIiIiIiIiIiIiIiIiKQ5w8OI9_K3--nJv1Qb5dNFha74kd60bHFpy6xySc3ySQwsMdQCe_GVhae_hwkb4asqkREREVL_b8qR4UoiIi0ber-T_pcTDPjT9v_wArlhAiIiIiIiIiIiIiIiIiLZF6K2sqm3bua60BLWsbRXqwxXFkLnY-JPTzhgLR9fhzSE_YLcKCD4KlERERUv8Ab8qR4UoiIi0besAT_pczdv8A6ft_-VywgRERERERERERERERERFkF0Kbnt2m6p9Bamq68UlBUXFtrrpSwvAgqmmEjiO-fmAz7eV9EDMeGuOCBj8fUELmREREVL_b8qR4UoiIi0besAR_pcz-f_gFv_yuWECIiIiIiIiIiIiIiIiIuSnnnp5o56eZ8UsTg-N7HFrmuB7EEeCPqvpd6fNbU24uymiNb0tQ6Vl4sVJUF7hhxcY2h-e5-bkDkexJHsrjoiIiKl_t-VI8KURERaNvV_8A9rmb_cFD_lcsIERERERERERERERERERS3yt43pBatOoekdljfE9h0xqS4Wscz2c14jqwQP3R_wClHt9QSs4URERFS_2_KkeFKIiItG_rAf7XE3-4Lf8A5XLB9EREREREREREREREREUt8ra56I2pbu-3bqaPkqy61001rucFO5o4x1ErZ45XNI8l7IYgQfHwxj95bS0RERFS_wBvypHhSiIiLRt6wP8Atcz_AO4Lf_lcsIERERERERERERERERERFnr6P-5dZo_qRr9BTOlFHrWzTQFpIDG1FMfixyHIySGiZgwcD4hJBwt17Hl2Sexb7LkRERFS_wBvypHhSiIiLRr6vzg7q7qG_Sw2_wDyuWEKIiIiIiIiIiIiIiIiIivn0WsrH9V21kdDK5lQdSUgif27Hlj7_ugjB8ecr6MYuOMg5JXIiIiKl_t-VI8KURERaPPWAs90o-rJ1yrKb4dJcNP0MlI_OfitZljj9sODv6LBpEREREREREREREREREUs7nus7PR_0db9RdU1XfK0P-PprTNXcKZjQCHufJDTkkEfuiY4wQeWM5GVu2jAGcBcqIiIqX-35UjwpRERFqP9aPb7UrtYaI3WdC-SwutxsImAbiOpEks7Wu7_ALzXOI9vkJ-gWsh3lQiIiIiIiIiIiIiIiIiePC2ieiDSRS3_AHZrJG_rIqO0RNz44vdUk_z-Qf1W2PAHgBSiIiKl_t-VI8KURERWL6zNoX759NeudvKWNz7jVW8VttDSGn9LpntnhZyPYB74-DneQyRxHcBfOpU00tLNLS1EL4pYnFj2PbhzXNJBBHsRggj6hdZERERERERERERERERFLO57rc_6RPT7rLanbbUe5etKCe3P18-hNto5QGyspIGyubM8cst-IZsNaW8uLWu8Pw3YQiIiIqX-35UjwpRERFQ4E9wF85_Wnt8NsOqLcPTA5_o5vU1fAX45cKhxmyAA0EfOQrFIiIiIiIiIiIiIiIiIsjegzYSk6g-o7T-kr1QipsNuD7vd2ui5xyU0OCI3jk3DZH8WE_3sL6EaKip7fTx0lJTxwwQMEcUcbA1kbAMBrQOwAHsF2kRERFS_2_KkeFKIiIi1k-sXsTopmhbX1B0VK-n1I250tkqnxn9XUwvjmcC8e7gWAAjvjstRqIiIiIiIiIiIiIiIilvlbjfRy2Obpba6_wC-N7tL4rtq2sdbrbLKzBFsgwS6M8eY-JOXB2SQ4QRkeDy2NIiIiIqX-35UjwpREREWC3rE9-keFzB41Zbs_YfBqP8AxC0gIiIiIiIiIiIiIiIiLnhiknkZFDGXyvcGMa1uSSTjGPckkAL6Ydi9GUG3uzuitFW6mZTwWeyUdKyMBw_ZhAcfm-YuJJJJ-quAiIiIipf7flSPClERERYl-qHpm36i6K9d1FYzMtlkt1ypHgf6uVtXDGSfryjke37cs-y0FoiIiIiIiIiIiIiIiK4Ow9hfqbenQ1iihfUPrL_QRtibL8IuAnaXfNxcBgAlfS5R05p4Y4md2MYG-AM4XbRERERQfClERERFb3ffbOi3k2e1jtfXSNjZqW01FCyYjPwZXsJilx_ceI3_AH4r5r77Y67TF_uenbxTiGutVTNRVUJIPw54nFj2_fi9p7-4H3X5KIiIiIiIiIiIiIiIr9dDFrmuvVttfTR0z5gb_A9_BpdxY0OcSePsMd19FYYAckDKrRERERQfClERERFQWM847LS96q3STHtNrob6aPa5untZ1z23Cla04orgWhxdk_uSnk4f3g77LX2iIiIiIiIiIiIiIiLMn0pdNVd-6wtP18dHLNTWW319dUzMYS2AfAc1hcT7F7w38kLe991KIiIiKD4UoiIiIitl1B7PWDfzZ7U21WoImGG-0T46ebGTTVbfnhmb_eY9rHAe4aQfK-dndXarWGzeuLpoDXVofQ3S1zGN7T-zKzlhsjCezmOHcH-q8UiIiIiIiIiIiIiIi28-jVsXd9M6Q1PvjqG200LNVCG22OQg_pDqWCWQ1Du4-WN8oiDcH5jCSewbnZeiIiIiKD4UoiIiIipLW-cDP1WM3Wt0d6V6p9vKqCKjp6LWtuhfNZLqWcXte1ufgSEd3Rv_AGT9CQR4WhbXOhdV7dalrtI61sFVaLvbZnQVFNUx8CHtPzY7fMMjsQfBC82iIiIiIiIiIiIiniVeDpp6dNY9S26FDt5o63Okg-Iye7V3Lgyhow4fEkc8hwacZDflcS7AHIEr6ItDaMsW32kbNofTVFHS2uyUkVFSQsYGhkbGtaOw7A4BP816VEREREVLlUiIiIiIoIGMYC1_-rxsW7XGxdHutp-0RyXLQ9aJa98UQ-K-glAjc4kDJEbxGe_YNLz7BaWfooREREREREREREWXPQP0TWzq-uOrTqXUlysVo05TU_GroIWPLqmV5wwh4wRwY8nHcdvqtvvTD0nbYdK2k59N6Ahq6mpuErJ7ldKx4dU1r2tIbkNHFrACSGtwASSr48W-eI_opRERERFS_wBlI8KURERERFbLqVsdZqTp13S0_bKX49dc9F3ukp4g3JfNJQzNjAH15FuF81JZjAIGRn-ePbHsuJEREREREREREU4JOMZJ-i33emLs6_aTpS0_UV1G6C76xml1JWtkbgtbNxbC0Z74-BHCeJ8Oc_6lZcYClERERERUv9vypHhSiIiIiIuGeJskT43NBDuxBGc5-q-fT1CNjrPsJ1Mag0tpkBtmurI71RQj_wCXZPnlCPbDXB2PoCPosaERERERERERERXS6Z9tZd2N-ND6CZQ_pUN0vNM2qjdEXsNO14fKHY8NMbXD7ZX0l0dHS0VLFQUcbIqeCMRxxsHZrQMAD6DHsu2iIiIiIipd5VSIiIiIiKl4JHZakvWk23qKfWOht1aWif8AAuFFPZ6uYMOBNG7mxpI9-D8DPY4K1juUIiIiIiIiIiKWraT6NOw1PUyao6h73SB76Od2nbKHju2Qsa-qlwfB4uiZn7ye4W10AY8KUREREREUHwpRERERERQfCtpv1svpDf7a29bWaxpA-hu1M5kE7Wgy0VQ1v6qeP-F7H4IJ7HBa7IJB-cjcHQ2ottNZ3nQOrrf-h3ixVj6KqiI8PaT3b_E09iCfYheaREREREREREX6thsVx1LeqDTtlo31NwuVVHR0sDG4dLK9wa1v5LnAfQdyvo86Y9nLfsLsZo_a6kDDNZrcxtbM1hb8ask_W1EmD7Oke4_YYH7qut4ClERERERFB8KURERERERUPaMf9q0K-qjRUVF1lapdQwxxuqqOhnqOAA5SfBA5Ox5PFre5WIiIiIiIiIiIizw9I7Y-TcPfup3JuNGySy6EpvjfrO7X1s7XMhb_ACDXv_4R9Vu0Y1oaAGgZyfH18rkRERERERFB8KURERERERUv_ZXz_wDqaVUtR1na9bIf9Q-kiZn-EU0axZRERERERERFLfK3VejltxX6V6crvrq4xiNutb26aiBHd9LSj4HxPtmUTAD-4D7rPweApRERERERFB8KURERERERUuWgD1NKSak6ztePnaR-kPpZWZ_hNOwD_KsWERERERERERSzOe2P5r6CPTe1nYdYdHugWWGl_RW2WkfaaqI4z-lQv_WPwPZznF_fueWfdZPDwpRERERERFB8KURERERERQfC0V-rdaZbb1gXKpdG4suFkoKhri3AJw5uAffHEZ_KwsRERERERERFLW8jhbwPSF0ZeNL9KEt-uTWti1XqSsulE0F2RA1kVOC4FvYmSnkPbII4n3KzmHhSiIiIiIiKD4UoiIiIiIih3L2AK1uesD073DWOhrPv5pqkM8-kmmivLGNy4UEjsxz9jjDHkBxAzxeD4BWnx_Y9lCIiIiIiIiAE-AvZbVbc3zdncKw7c6ZhL7jqCsjpISA1wY1x-aQ5LQA0Bzjlzezce6-krbLQdn2v2909t3p-PhbtN22ntlODyyY4WBuXF3ck4Jz9yvWIiIiIiIiKk9m91UiIiIiIiIvyNQWW1als9dp6-UEVbbrnBLSVdPMzMcsUjC2RjgfGWkj-a-errJ6arn0y72XfRP6LUO0_VPNbp-rkaT-kUb3EtbyPZz4-7HD3wD7qwhGCoRERERERFysaScNHc4x9TnwAB7rbp6UHR3XaNtMfUxr-kkp7re4Hw6ft09O5j4KR5HKrfybyDpACGYwOB5ZcHgN2Vsj4jw3I98LkREREREREUO8KURERERERFxujBdkBv9PvlWK6t-lrSPVTttVaPvcjKK9UbXzWW6tj5voqotIHJo7ujPy8m5yQAW9wFoK3a2h1zstru5bdbgWV1BeLbIWOaPmjmZjLZYXjtJG4fMHDtg9w0gtb4VERERERFW1vI4wM59x5P0wFsY9OD0-nbmVUW9u9llqYNMUE7HWW0VVM-M3aQAOFQ5r2t5Uw5ANIyHu5AEBpzuGpqSnpYWQU8TI44wGsYxoDWgYwAB48D-i5lwzzfBjMjwQ0dj38D6rmBBGQpRERERERUuVSIiIiIiIijAVBjjznH8ljH1vdG2neq_b6aGgNDbtcWmNz7FdZmu4Oe05dTTFmXfDfhwyA4sc4O4u4lrtD2tdBam241Pc9F67sdVZr3Z5TT1VFURkOa5pGSHDIcO-Q4ZY5uHNJBbnzCIiIiIuwyB0rmxxMLnyENYGjJJzjx5yfYBbKPT-9NS5alr6bePqJ05PQWanl5WfTlbCY5q9zXYM1RG7Do48ggMe0OeByxxLCduNPSU1LDHTUsLI4omNZHG1oDWNHgADsAO2AudF1bhEJ6OaPxyaueP8AZH4VaIiIiIiKD4QeFKIiIiIiIiKkxtOcjOexWJXXL0O6b6qtKS3myCltmv7PD_6qub_ljq2gl36LUOaCSwjs1xBLCQ75hyadGWtdC6o261PcdFa209VWe-WyZ1PVUdUwtkicDnIPhwx3Dh8jm_M0kEFebREREXttsdo9w949U0-i9sdIVt_vFV-xDTsDWN7HLnyPIZG3AOXOcACOxW4Xo49MbQexX6Jrndea36y1q10dRCGwk0FqkDW4bE13eV4eXfrHNHgYazB5Z1NiYzw3_wA_-QFWiLp3OobSUM1S5pIY3OFXR1LKqmjqIs8XDK7KIiIiIiKD4QeFKIiIiIiIiIqTGwnJHdYzdXHRDtj1W2eSpu0LLJrOkpzBbL7TNPJuSHNZOwdpo8g9vLQ5xDgVpH376cN0um3WMujNzLCynlIzS19MXS0VczyHwykAkZyMENcMfM0ZVqkRF-9pbROrNcXKKyaM0vc75cJjxjpbdSSVEr_P7rAT7fRbD-nD0etYXusotT9RV5prNaXRxyiwW2V0lbLzbksnlDeEHAkAhpkLiHAOaAHO2f7VbN7Z7J6dZpbbDRtvsFC3HJtNCBJMck8pHkc5CMnu4nyV7oxsJyR7Y_kqkRF-de43SW2ZjScubxwps0TobdFER-x8o-4X6CIiIiIiKD4QeFKIiIiIiIiIi43MZ_C0kHOCPfOf-9eK3R2o0DvNpOo0XuLp6kvNpqSCIphng8HLZGOxlrh7YWqff30e917Dfam47AVtv1RZJBzgt1dWx0tbCP4echEcn55NKsHffTa61tPUba2v2IuErC7iGUNyoa2TH14QTOd_2L0GjvSy6ydUy0Ir9urdp2lrT3qrxeKdn6O36viidJNn-6Iy77LL_an0X9urLURXHeDcm5akDTGXUFppv0GD_Vu5tdI5z5HjmQWubwOAAR3Kz_0FtbtxtfQOoNA6Ls9hhkH600dGyF0p793uABd5Pn6r1oA84GVJa0jBaMeMYUoiIutVBrgIyc8jlc7I2xtDGjAHYKpERERERFS_2VSIiIiIiIiIoyPqqeQHknzjv2yfosMerP1Ldr-m67zaFsloqNXa0pJWsrbfE91NBQsc3kHSTFjg52MYY1pJzklowHYEW31O-qPWe5tulr7pSGy3K4w07rHQUkbIy172scyN0hB5HmOPxHgZxlwGVmlon1Dat9caPU2i77bqP9NjoKesvVAaKOsncSGmLk4S_NxyOTGj5mtPFxIWVO3m_Wgdw6iO2W2udS18jMtpKgcXH7NPh5_C89v31S6F6cG09fuhbrrQ2SsIihukFO-eJ0zskR8WNc4HDfcYXk9p_UI6Wt4LrFZNP7iQUFzmkbBDT3WN1G6aR_Li2P4oaXE474BA7K7Otd7dr9t7tb7Nr3Wtt09U3iRsFA64yNhjqZXfstY4kNJ-2c_de6jmbIxpjfyyAflPYg-D79vwVzoiIqSTnHsfP2XWj5SzlxGGtHFq7Q8KUREREREUHwpRERERERERUOe0ZyccV0prrRR1LaH9JidVvYZGU4lAkcwEAuAzkgZ84UVdBHXiN8kkzPhP5sDJC0h31OPP-HwrNdQ_R1sn1L0Ubdw9Mxi60w5U91ocQVjPlxxdI0ZkZ_dcMfZYfV3QppDYrU9tr6WzsFNDHIyKseBUMrHcg6N7zICWSMyRluMg9uQ-Zemm0YZHucyjfLG45A98E5Bz-e671m0XdLTXNuVrlfTzMla6J0bhlp5ec_w_fysgyNE9Quga_afeK00VYKyE07hI9g-K8tLRLA4jkyUcsg8QR9Fp561uirVXSdq1tRHI-7aLvNRP_Y9wawh0QD3EU84ycPEfD5s4d3cOP7Kyz6It_wDbrqy2nl6P-peKnuFwgphDYq2Zz3T1ELIwQRMQ4MqI8AtJdykJwR2Oe3sr1Kbj9Bu8svSt1TX9120Y94n09qh8j5P0allLhFK4nlJ8BxaWmMjMLmuPJzBk7N7bdKO60cFxttdFWU1UxssE1O8PjkjcAWua4EhwI75HbAPgr9FERcbwS1wB8qpjA1vHAVSIiIiIiIoPhSiIiIiIiIoz3wsaetTrD050nbdRXiWjbdtVXxz6axWwkiN8gALpp3js2KMFpIBDnOIa3A5Obpig6vt9nb6WzqEu-uK65altVS18bZZCynfS_E5vozGwgNgfgsLB4BGDyaCt7fT_ANQOh-orQFt15oe4NkZUs_XUriBNSy4AfE8cjxcwnDs59iOQc1xuuCPYffuuncbXQXWjkt9xpYqiCVvF8cgyC3_xVotS7P01kY64Wdsk9FG0l0HlzIwc_wAxj38q1N5raekklbA0kRDPYHt9sH3Xgq_VNypK_wCJQz_Alxhk4Hzxj7B3n-avJovXmi9-NLVWym7Vtprq25Uj4pWzs5R1LQcA8v3ZM9wR3WofrD6a9Q9HO99LRWO51X9mTPbedNXYEfFjEcmWjkDkyRu4DkQ390-5V1d-N-f9Nnpbtd7vNhfJujtrXRw3F9BTiT-0rdMw86oNYDJGwGPLwQGB2HZ-YNbz-m71rXjYvXNFsvuHeJ36AvtSYKaOdhkNprZX4D2ZIdHE97svGCATyw353HddHMyoa2SKUPYQCHNdnIPf27dx3BC7CIoPhSiIiIiIiIoPhSiIiIiIiKD4XndRajmoHCgtdM-orZewAHyxD-In3_Cxz3B6OND7t6hq9TboWAX-5V8UURfXSOPwmxhwAiHIBgBe5zgMciQT4WEG4fpOXG06irRp3XE9Nb5WE0UdVSfFfE4Pb2Lw5vNoYSOzeQI5HsDn9PoWqdebJ6m1PtFqGOvt1609Utq3Rl7H0dSyY_DjkiOA8tcGD-72w4NcHAbQdu9yqLWtC0VLBS3AOLHRcgQ8t8lufZe4B9vB_qqXxh4ILWkHyCPKsHvft1Pb4KjVVjaXQPDnVEAzyDych39eyw43C1zaND22ovl9uUVFBE0yEzYa9zAPPEnOT44jk4n9kFYma162b2auKr2ypqy1V1LURVEVbO5rXtLC7kx0eXZGC0ghzSMHOVfffzeK19dXRIdezUcVFuDtNcIJ71SjLWzUs36kyw4zzDvkPEkEOa4eMcrlenJ0M610Vp2Xdrcdz7XU6rpGMpbO8YmhpefJskzfLZHHDhH5DcBwDiQ3LbXvRbsVuLaain1HoW0VlwqHtlkrn0zWTOewAMcXs_WEYABHL2-y49kbxqva69Q7F63NZX2-jo2u05fpxI7lTxlsZpKiVwwZWggtdyy5pII5NJdkKHeD7H7qpERERERERERUuUjwpRERERERUPaXsLQ4j7grgp7fS0vzRRAPPfk7uf6rscV0LpaYLpCY5gAR2Y4DuFiP1PbOUWltaaf3qs9DM6RwfY7t-h07nvkE5DYJZQHD5GPBbni7HPPysa4ho-5VX6RDLRu4SR4EQhdwIz57lZH6B1z_AG7Rspbm9jatrMveHDB-xx4K9uD9e2fGCutXUdNXU0tFWRMkhnHGRjh5B8fzz3_K0keqBt1U7cbhWm0Ptc8lNI2eeiujiXNkgJaTEfbmHZJHjzhYPOc_JHJ3bHv9PC2U-jztJqW56s1huNX2uJ2kn28WOYyO5ionJZJwDAD-yOJcTjGQAPPHbpFTwxwtihaAwM4tbjtj6YXKY2kEAYz9F5_VulKHVFtdTTt-HNH88Ew8xSfULq6Mu1wbG_TuocC50AwXAYE8X7rx9Tjz916nLs-FWiIiIiIiIiKl_spHhSiIiIiIiKMBSowfqvxdU6coNVWCv07XtBhuETo3nGcEtwHfkEAg_ZYn26xXDQl-msN2gIkp5CwF2eTmt_ex44kYcD58hfvamrqegsT6p1RiWHlIwDLMOHjBH1X73T_1N2fXlSNKXi6U0lyc-RlJUtfls72OLHxHsAHNeOGM5LwW-V39-t_aPbyGutc1bFQVVG01LpZZOLGRBpPxeZ7YbguJOAOBBI-bOInWXeouqzovuO49rt8kGodt70aW-UrYHu5RxOLDM3IB-E6N7Zg4FzQ1xwTjksC-k3pV1t1Vbix6V09G6js1Fxmvd2czLKSE9-Lc9nSu7ho_Lj2AX0A7cbb6O2p0ZbNCaHssFss9ogEFPDG3j2Hklx7ucTlxd5JJPuvW4HjClUkDzgdvC_MuNmiqqmK5RH4dVB3ZJ9R_Cft9l3YJXyN_WDi8ftN_h_n7rsIiIiIiIiIipf7flSPClEREREREREUcW5zjurC70X-x2_dHQmiX2urqrxreWppqZ8FOHsp2UzPiPmmPJpbGAex75JwvH9RmnnaC25rtUagmdFZ6KJ1RVPow97qYNbycSA3Lm8QQMd8rSnrjdJzt1arXm11TX2FrHOdTSh7mTlzub5HuaXODS573HA-VpwQFslgvtn64emHSu5d6t0N01VpCWGh1FR8S7408JAZUcPl-U8g_95gD3Ak91cTpg6drTSaH3O2baKqm05q23_BdTtbxjpjIz4buBHcuyS8vdl3doPFvEDJjp86e9uOm_Q8eiNu7WYIHETVVTJl0tVNxa1z3P9yeOQB27lXUDGNxxYBjsMDwqkRU8fupwPOApRERERERERFS_wBvypHhSiIiIiIiIijIXE57I2Oke_i1uS4k9gB5OT7LGbYvWOm9-9_debqWuOtmodBudo2gnnje2CSUPL6qWHm0ZLXMYwu9-IPuOX6HVVufbLJpQ6ZLppZq95iayGN0oyGucS4gfKz5S3m75cuxnl2WgnWNqo7Lqm8Wukke9lDcqqlIbFxY1rJS1hB5OzyDc_b2yrrdL3VTrDpgv13r7NRtu1qvVukpqu1TPLKeaXAEUj_lJzGQR2-p-gW-zY-Ww3XazTOptOvMtDqK20t5hlexzC9tREJWkBwBxh3YFvurghjB4aB49voqkRERERERERERERQfClEREREREREXXMxbOIPhvy5vLljsD9FwXO20t3oKi2V8ZdBUxvjkDXFp4Hz3C8PT6Q0ztNo8WDbPRQt9NM88o7ZSPc8y8cCWV2C-RxIAdJIS45ySsO-qay71DQt0u2ituNU3-7syKWlprJU1L-T3NbyDGMJeG5JIA7gLWTF0l9WV7ufw3dO2576qrkc901Xpiuja5zgS4vlkiABPfJc4ZJ-qyzsXp7a10L0xul1FoK7XDcfcu7Wu2QQ0Vtmq3aYoHTtMstV8Np4AYDnjsAAAXHBW2bQGnrLpDR9n0hpygkorVp6jhtFFC9paWwUzBCwDPzEAMADj3d5XqERERERERERERERFB8KURERERERERUDwPypb4_mf-9daf_3ln-GT_KFVL5f_AIz_APjU_wDWf8X_ADKlnhv5b_yLl_6w_wCP_lXKiIiIiIiIiIiIiIv_2Q==',
                },
                {
                  type: 'default',
                  identifier: 'expiry_date',
                  label: 'Expiry Date',
                  value: '2025-04-29',
                },
                {
                  type: 'default',
                  identifier: 'issuing_country',
                  label: 'Issuing Country',
                  value: 'LV',
                },
                {
                  type: 'default',
                  identifier: 'issuance_date',
                  label: 'Issuance Date',
                  value: '2025-01-29',
                },
                {
                  type: 'default',
                  identifier: 'given_name',
                  label: 'Given Name(s)',
                  value: 'MĀRA',
                },
                {
                  type: 'default',
                  identifier: 'issuing_authority',
                  label: 'Issuance Authority',
                  value: 'PMLP',
                },
                {
                  type: 'default',
                  identifier: 'birth_date',
                  label: 'Birth Date',
                  value: '1982-12-12',
                },
                {
                  type: 'default',
                  identifier: 'nationality',
                  label: 'Nationality',
                  value: 'LV',
                },
                {
                  type: 'default',
                  identifier: 'personal_administrative_number',
                  label: 'Person unique personal administrative number',
                  value: '32015372306',
                },
                {
                  type: 'default',
                  identifier: 'birth_country',
                  label: 'Birth Country',
                  value: 'AI',
                },
                {
                  type: 'default',
                  identifier: 'family_name',
                  label: 'Family Name(s)',
                  value: 'PARAUDZIŅA',
                },
                {
                  type: 'default',
                  identifier: 'birth_place',
                  label: 'Birth Place',
                  value: 'ANGILJA',
                },
              ],
            },
            {
              meta: {
                id: 'Document_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                documentIdentifier: 'mDL',
                issuerDisplay: {
                  issuingAuthority: 'CSDD',
                  issuerCountry: 'LV',
                },
                documentDisplay: {
                  backgroundColor: null,
                  textColor: null,
                  description1: 'LV',
                  description2: 'B, BE, C, CE, D',
                  description3: 'Dancotājs',
                  name: null,
                },
                issuanceState: 'Issued',
                hasExpired: false,
                isFavorite: true,
                expirationDate: '2025-02-26',
                issuanceDate: '2025-02-19',
                displayNumber: 'WE000109',
              },
            },
            {
              meta: {
                id: 'Document_EudiWalletDocumentManager_2d78b8b7-94ad-4d2e-a82b-90b9098c61c1',
                documentIdentifier: 'Diploma',
                issuerDisplay: {
                  issuingAuthority: 'RTU',
                  issuerCountry: 'LV',
                },
                documentDisplay: {
                  backgroundColor: null,
                  textColor: null,
                  description1:
                    'Mechanics and Metal Processing, Heat Power Engineering, Heat Technology, and Mechanical Engineering',
                  description2: 'Bachelor degree of engineering science in mechanical engineering',
                  description3: null,
                  name: null,
                },
                issuanceState: 'Issued',
                hasExpired: false,
                isFavorite: true,
                expirationDate: '',
                issuanceDate: '2024-11-04T12:05:52+01:00',
                displayNumber: '320153-72306',
              },
            },
            {
              meta: {
                id: 'Document_EudiWalletDocumentManager_a67bd590-b31d-4348-b60e-54b31e5da796',
                documentIdentifier: 'eu.digimaks.esign',
                issuerDisplay: {
                  issuingAuthority: '',
                  issuerCountry: '',
                },
                documentDisplay: {
                  backgroundColor: null,
                  textColor: null,
                  description1: null,
                  description2: null,
                  description3: null,
                  name: null,
                },
                issuanceState: 'Issued',
                hasExpired: false,
                isFavorite: true,
                expirationDate: '2025-11-04T12:05:52+01:00',
                issuanceDate: '2024-11-04T12:05:52+01:00',
                displayNumber: '545353543', // todo
              },
              documentDetails: [
                {
                  type: 'default',
                  identifier: 'sid',
                  label: 'sid',
                  value: 'cZ5OztvziLYzhKFdsuL5pC-4z_Q',
                },
                {
                  type: 'default',
                  identifier: 'cn',
                  label: 'cn',
                  value: 'MĀRA PARAUDZIŅA',
                },
                {
                  type: 'default',
                  identifier: 'expiresOn',
                  label: 'expiresOn',
                  value: '2028-03-05T09:49:10',
                },
                {
                  type: 'default',
                  identifier: 'issuedOn',
                  label: 'issuedOn',
                  value: '2025-03-05T09:49:10',
                },
                {
                  type: 'default',
                  identifier: 'type',
                  label: 'type',
                  value: 'eSign',
                },
              ],
            },
            {
              meta: {
                id: 'Document_EudiWalletDocumentManager_a67bd590-b31d-4348-b60e-54b31e5da755',
                documentIdentifier: 'eu.digimaks.eseal',
                issuerDisplay: {
                  issuingAuthority: '',
                  issuerCountry: '',
                },
                documentDisplay: {
                  backgroundColor: null,
                  textColor: null,
                  description1: null,
                  description2: null,
                  description3: null,
                  name: null,
                },
                issuanceState: 'Issued',
                hasExpired: false,
                isFavorite: true,
                expirationDate: '2025-11-04T12:05:52+01:00',
                issuanceDate: '2024-11-04T12:05:52+01:00',
                displayNumber: '545353543', // todo
              },
              documentDetails: [
                {
                  type: 'default',
                  identifier: 'sid',
                  label: 'sid',
                  value: 'cZ5OztvziLYzhKFdsuL5pC-4z_Q',
                },
                {
                  type: 'default',
                  identifier: 'cn',
                  label: 'cn',
                  value: 'SIA DEMO QSEAL: eZīmogs',
                },
                {
                  type: 'default',
                  identifier: 'expiresOn',
                  label: 'expiresOn',
                  value: '2028-03-05T09:49:10',
                },
                {
                  type: 'default',
                  identifier: 'issuedOn',
                  label: 'issuedOn',
                  value: '2025-03-05T09:49:10',
                },
                {
                  type: 'default',
                  identifier: 'type',
                  label: 'type',
                  value: 'eSeal',
                },
              ],
            },
          ],
        },
      },
    },
    getDocumentDetails: {
      response: [
        {
          id: 'string',
          status: 'SUCCESS',
          data: {
            meta: {
              id: 'wYJMnQeApGnc',
              documentIdentifier: 'eu.europa.ec.eudi.pid.1',
              issuerDisplay: {
                issuingAuthority: 'PMLP',
                issuerCountry: 'LV',
              },
              documentDisplay: {
                backgroundColor: null,
                textColor: null,
                description1: 'LV',
                description2: null,
                description3: null,
                name: null,
              },
              issuanceState: 'Issued',
              hasExpired: false,
              isFavorite: false,
              expirationDate: '2025-05-20',
              issuanceDate: '2025-02-19',
              displayNumber: '32015372306',
            },
            documentDetails: [
              {
                type: 'default',
                identifier: 'age_over_18',
                label: 'Age Over 18',
                value: 'true', // 'true', 'false'
              },
              {
                type: 'default',
                identifier: 'expiry_date',
                label: 'Expiry Date',
                value: '2025-04-29',
              },
              {
                type: 'default',
                identifier: 'issuing_country',
                label: 'Issuing Country',
                value: 'LV',
              },
              {
                type: 'default',
                identifier: 'issuance_date',
                label: 'Issuance Date',
                value: '2025-01-29',
              },
              {
                type: 'default',
                identifier: 'given_name',
                label: 'Given Name(s)',
                value: 'MĀRA',
              },
              {
                type: 'default',
                identifier: 'issuing_authority',
                label: 'Issuance Authority',
                value: 'PMLP',
              },
              {
                type: 'default',
                identifier: 'birth_date',
                label: 'Birth Date',
                value: '1982-12-12',
              },
              {
                type: 'default',
                identifier: 'nationality',
                label: 'Nationality',
                value: 'LV',
              },
              {
                type: 'default',
                identifier: 'personal_administrative_number',
                label: 'Person unique personal administrative number',
                value: '32015372306',
              },
              {
                type: 'default',
                identifier: 'birth_country',
                label: 'Birth Country',
                value: 'AI',
              },
              {
                type: 'default',
                identifier: 'family_name',
                label: 'Family Name(s)',
                value: 'PARAUDZIŅA',
              },
              {
                type: 'default',
                identifier: 'birth_place',
                label: 'Birth Place',
                value: 'ANGILJA',
              },
            ],
          },
        },
        {
          id: 'string',
          status: 'SUCCESS',
          data: {
            meta: {
              id: 'Document_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
              documentIdentifier: 'mDL',
              issuerDisplay: {
                issuingAuthority: 'CSDD',
                issuerCountry: 'LV',
              },
              documentDisplay: {
                backgroundColor: null,
                textColor: null,
                description1: 'LV',
                description2: 'B, BE, C, CE, D',
                description3: 'Dancotājs',
                name: null,
              },
              issuanceState: 'Issued',
              hasExpired: true,
              isFavorite: false,
              expirationDate: '2025-02-26',
              issuanceDate: '2025-02-19',
              displayNumber: 'WE000109',
            },
            documentDetails: [
              {
                type: 'default',
                identifier: 'un_distinguishing_sign',
                label: 'UN distinguishing sign',
                value: 'LV',
              },
              {
                type: 'default',
                identifier: 'driving_privileges',
                label: 'Categories of vehicles',
                value: 'B, BE, C, CE, D',
              },
              {
                type: 'default',
                identifier: 'expiry_date',
                label: 'Date when mDL expires',
                value: '2025-02-05',
              },
              {
                type: 'default',
                identifier: 'document_number',
                label: 'Licence number',
                value: 'WE000109',
              },
              {
                type: 'default',
                identifier: 'personal_administrative_number',
                label: 'Person unique personal administrative number',
                value: '32015372306',
              },
              {
                type: 'default',
                identifier: 'age_over_18',
                label: 'Age attestation: Nearest “true” attestation above request',
                value: 'false',
              },
              {
                type: 'default',
                identifier: 'given_name',
                label: 'Given names',
                value: 'SANDAMU HASIKA RATHMALGODA',
              },
              {
                type: 'default',
                identifier: 'issuing_country',
                label: 'Issuing country',
                value: 'LV',
              },
              {
                type: 'default',
                identifier: 'issue_date',
                label: 'Date of issue',
                value: '2025-01-29',
              },
              {
                type: 'default',
                identifier: 'birth_date',
                label: 'Date of birth',
                value: '1965-02-15',
              },
              {
                type: 'default',
                identifier: 'family_name',
                label: 'Family name',
                value: 'RATHMALSODA HERANISE MIDIANSEHANU',
              },
              {
                type: 'default',
                identifier: 'issuing_authority',
                label: 'Issuing authority',
                value: 'Test QEAA issuer',
              },
              {
                type: 'default',
                identifier: 'portrait',
                label: 'Portrait of mDL holder',
                value: 'Shown above',
              },
            ],
          },
        },
        {
          id: 'string',
          status: 'SUCCESS',
          data: {
            meta: {
              id: 'Document_EudiWalletDocumentManager_2d78b8b7-94ad-4d2e-a82b-90b9098c61c1',
              documentIdentifier: 'Diploma',
              issuerDisplay: {
                issuingAuthority: 'RTU',
                issuerCountry: 'LV',
              },
              documentDisplay: {
                backgroundColor: null,
                textColor: null,
                description1:
                  'Mechanics and Metal Processing, Heat Power Engineering, Heat Technology, and Mechanical Engineering',
                description2: 'Bachelor degree of engineering science in mechanical engineering',
                description3: null,
                name: null,
              },
              issuanceState: 'Issued',
              hasExpired: false,
              isFavorite: false,
              expirationDate: '',
              issuanceDate: '2024-11-04T12:05:52+01:00',
              displayNumber: '320153-72306',
            },
            documentDetails: [
              {
                type: 'default',
                identifier: 'awardingBody_countryCode',
                label: 'Awarding body country code',
                value: 'LV',
              },
              {
                type: 'default',
                identifier: 'family_name',
                label: 'The family name of the person',
                value: 'Paraudziņa',
              },
              {
                type: 'default',
                identifier: 'issuing_authority',
                label: 'Issuing authority',
                value: 'RTU',
              },
              {
                type: 'default',
                identifier: 'creditValue',
                label: 'Credit system',
                value: 'ECTS',
              },
              {
                type: 'default',
                identifier: 'eqfLevel',
                label: 'EQF level',
                value: 'Level 6',
              },
              {
                type: 'default',
                identifier: 'nationalID',
                label: 'The national identifier of the person',
                value: '320153-72306',
              },
              {
                type: 'default',
                identifier: 'thematicArea',
                label: 'Thematic area',
                value:
                  'Mechanics and Metal Processing, Heat Power Engineering, Heat Technology, and Mechanical Engineering',
              },
              {
                type: 'default',
                identifier: 'citizenshipCountryCode',
                label: 'Citizenship country code',
                value: 'LV',
              },
              {
                type: 'default',
                identifier: 'awardingBody_legalName',
                label: 'Awarded by',
                value: 'Rīgas Tehniskā universitāte',
              },
              {
                type: 'default',
                identifier: 'validFrom',
                label: 'Valid from',
                value: '2024-06-20T00:00:00+03:00',
              },
              {
                type: 'default',
                identifier: 'maximumDuration',
                label: 'Maximum duration in months',
                value: 'P36M',
              },
              {
                type: 'default',
                identifier: 'title',
                label: 'Achievement title',
                value: 'Bachelor degree of engineering science in mechanical engineering',
              },
              {
                type: 'default',
                identifier: 'creditPoint',
                label: 'ECTS',
                value: '240',
              },
              {
                type: 'default',
                identifier: 'awardingBody_registration',
                label: 'The legal identifier of the awarding body',
                value: '90000068977',
              },
              {
                type: 'default',
                identifier: 'issuanceDate',
                label: 'Issuance date',
                value: '2024-11-04T12:05:52+01:00',
              },
              {
                type: 'default',
                identifier: 'nqfLevel',
                label: 'NQF level',
                value: 'LQF Level 6',
              },
              {
                type: 'default',
                identifier: 'type',
                label: 'The type of credential',
                value: 'LearningAchievement',
              },
              {
                type: 'default',
                identifier: 'issued',
                label: 'Issuance date',
                value: '2024-11-04T12:05:52+01:00',
              },
              {
                type: 'default',
                identifier: 'given_name',
                label: 'The given name(s) of the person',
                value: 'Māra',
              },
            ],
          },
        },
        {
          id: 'string',
          status: 'SUCCESS',
          data: {
            meta: {
              id: 'Document_EudiWalletDocumentManager_a67bd590-b31d-4348-b60e-54b31e5da796',
              documentIdentifier: 'eSign',
              issuerDisplay: {
                issuingAuthority: '',
                issuerCountry: '',
              },
              documentDisplay: {
                backgroundColor: null,
                textColor: null,
                description1: null,
                description2: null,
                description3: null,
                name: null,
              },
              issuanceState: 'Issued',
              hasExpired: false,
              isFavorite: true,
              expirationDate: '2025-11-04T12:05:52+01:00',
              issuanceDate: '2024-11-04T12:05:52+01:00',
              displayNumber: '545353543', // todo
            },
            documentDetails: [
              {
                type: 'default',
                identifier: 'sid',
                label: 'sid',
                value: 'cZ5OztvziLYzhKFdsuL5pC-4z_Q',
              },
              {
                type: 'default',
                identifier: 'cn',
                label: 'cn',
                value: 'MĀRA PARAUDZIŅA',
              },
              {
                type: 'default',
                identifier: 'expiresOn',
                label: 'expiresOn',
                value: '2028-03-05T09:49:10',
              },
              {
                type: 'default',
                identifier: 'issuedOn',
                label: 'issuedOn',
                value: '2025-03-05T09:49:10',
              },
              {
                type: 'default',
                identifier: 'type',
                label: 'type',
                value: 'eSign',
              },
            ],
          },
        },
        {
          id: 'string',
          status: 'SUCCESS',
          data: {
            meta: {
              id: 'Document_EudiWalletDocumentManager_a67bd590-b31d-4348-b60e-54b31e5da755',
              documentIdentifier: 'eSeal',
              issuerDisplay: {
                issuingAuthority: '',
                issuerCountry: '',
              },
              documentDisplay: {
                backgroundColor: null,
                textColor: null,
                description1: null,
                description2: null,
                description3: null,
                name: null,
              },
              issuanceState: 'Issued',
              hasExpired: false,
              isFavorite: true,
              expirationDate: '2025-11-04T12:05:52+01:00',
              issuanceDate: '2024-11-04T12:05:52+01:00',
              displayNumber: '545353543', // todo
            },
            documentDetails: [
              {
                type: 'default',
                identifier: 'sid',
                label: 'sid',
                value: 'cZ5OztvziLYzhKFdsuL5pC-4z_Q',
              },
              {
                type: 'default',
                identifier: 'cn',
                label: 'cn',
                value: 'SIA DEMO QSEAL: eZīmogs',
              },
              {
                type: 'default',
                identifier: 'expiresOn',
                label: 'expiresOn',
                value: '2028-03-05T09:49:10',
              },
              {
                type: 'default',
                identifier: 'issuedOn',
                label: 'issuedOn',
                value: '2025-03-05T09:49:10',
              },
              {
                type: 'default',
                identifier: 'type',
                label: 'type',
                value: 'eSeal',
              },
            ],
          },
        },
        {
          id: 'string',
          status: 'SUCCESS',
          data: {
            meta: {
              id: 'Document_EudiWalletDocumentManager_2d78b8b7-94ad-4d2e-a82b-90b9098c61c2',
              documentIdentifier: 'Signature',
              issuerDisplay: {
                issuingAuthority: 'RTU',
                issuerCountry: 'LV',
              },
              documentDisplay: {
                backgroundColor: null,
                textColor: null,
                description1: 'Signature',
                description2: null,
                description3: null,
                name: null,
              },
              issuanceState: 'Issued',
              hasExpired: false,
              isFavorite: false,
              expirationDate: '',
              issuanceDate: '2024-11-04T12:05:52+01:00',
              displayNumber: '320153-72306',
            },
            documentDetails: [],
          },
        },
      ],
    },
    getDocumentOptions: {
      request: {
        id: 'string',
        func: 'getDocumentOptions',
        data: null,
      },
      response: {
        id: 'string',
        status: 'SUCCESS', // error
        data: {
          options: [
            {
              text: 'mDL',
              type: 'eu.europa.ec.eudi.mdl_mdoc',
              exists: 'false',
            },
            {
              text: 'PID',
              type: 'eu.europa.ec.eudi.pid_mdoc',
              exists: 'true',
            },
            {
              text: 'Diploma',
              type: 'eu.europa.ec.eudi.rtu_diploma_mdoc',
              exists: 'false',
            },
            {
              text: 'eSign',
              type: 'eSign',
              exists: 'false',
            },
            {
              text: 'eSeal',
              type: 'eSeal',
              exists: 'false',
            },
          ],
        },
      },
    },
    getRequestDocuments: {
      request: {
        id: 'string',
        func: 'getRequestDocuments',
        data: null,
      },
      response: {
        id: 'string',
        status: 'SUCCESS',
        data: {
          vendorKey: 'eudi-remote-verifier',
          quickFlowAvailable: false,
          savedSelectionApplied: false,
          verifierName: 'EUDI Remote Verifier',
          verifierIsTrusted: true,
          documents: [
            {
              fields: [
                {
                  checked: true,
                  elementIdentifier: 'family_name',
                  enabled: true,
                  id: 'family_namewYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'Family Name(s)',
                  value: 'PARAUDZIŅA',
                },
                {
                  checked: true,
                  elementIdentifier: 'given_name',
                  enabled: true,
                  id: 'given_namewYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'Given Name(s)',
                  value: 'MĀRA',
                },
                {
                  checked: true,
                  elementIdentifier: 'birth_date',
                  enabled: true,
                  id: 'birth_datewYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'Birth Date',
                  value: '1982-12-12',
                },
                {
                  checked: true,
                  elementIdentifier: 'age_over_18',
                  enabled: true,
                  id: 'age_over_18wYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'Age Over 18',
                  value: 'true',
                },
                {
                  checked: false,
                  elementIdentifier: 'age_in_years',
                  enabled: false,
                  id: 'age_in_yearswYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'age_in_years',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'age_birth_year',
                  enabled: false,
                  id: 'age_birth_yearwYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'age_birth_year',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'family_name_birth',
                  enabled: false,
                  id: 'family_name_birthwYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'family_name_birth',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'given_name_birth',
                  enabled: false,
                  id: 'given_name_birthwYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'given_name_birth',
                  value: 'Not available',
                },
                {
                  checked: true,
                  elementIdentifier: 'birth_place',
                  enabled: true,
                  id: 'birth_placewYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'Birth Place',
                  value: 'ANGILJA',
                },
                {
                  checked: true,
                  elementIdentifier: 'birth_country',
                  enabled: true,
                  id: 'birth_countrywYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'Birth Country',
                  value: 'AI',
                },
                {
                  checked: false,
                  elementIdentifier: 'birth_state',
                  enabled: false,
                  id: 'birth_statewYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'birth_state',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'birth_city',
                  enabled: false,
                  id: 'birth_citywYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'birth_city',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_address',
                  enabled: false,
                  id: 'resident_addresswYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'resident_address',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_country',
                  enabled: false,
                  id: 'resident_countrywYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'resident_country',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_state',
                  enabled: false,
                  id: 'resident_statewYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'resident_state',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_city',
                  enabled: false,
                  id: 'resident_citywYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'resident_city',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_postal_code',
                  enabled: false,
                  id: 'resident_postal_codewYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'resident_postal_code',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_street',
                  enabled: false,
                  id: 'resident_streetwYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'resident_street',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_house_number',
                  enabled: false,
                  id: 'resident_house_numberwYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'resident_house_number',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'gender',
                  enabled: false,
                  id: 'genderwYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'gender',
                  value: 'Not available',
                },
                {
                  checked: true,
                  elementIdentifier: 'nationality',
                  enabled: true,
                  id: 'nationalitywYJMnQeApGnc',
                  isRequired: false,
                  readableName: 'Nationality',
                  value: 'LV',
                },
                {
                  checked: true,
                  elementIdentifier: 'issuance_date',
                  enabled: false,
                  id: 'issuance_datewYJMnQeApGnc',
                  isRequired: true,
                  readableName: 'Issuance Date',
                  value: '2025-01-29',
                },
                {
                  checked: true,
                  elementIdentifier: 'expiry_date',
                  enabled: false,
                  id: 'expiry_datewYJMnQeApGnc',
                  isRequired: true,
                  readableName: 'Expiry Date',
                  value: '2025-04-29',
                },
                {
                  checked: true,
                  elementIdentifier: 'issuing_authority',
                  enabled: false,
                  id: 'issuing_authoritywYJMnQeApGnc',
                  isRequired: true,
                  readableName: 'Issuance Authority',
                  value: 'PMLP',
                },
                {
                  checked: false,
                  elementIdentifier: 'document_number',
                  enabled: false,
                  id: 'document_numberwYJMnQeApGnc',
                  isRequired: true,
                  readableName: 'document_number',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'administrative_number',
                  enabled: false,
                  id: 'administrative_numberwYJMnQeApGnc',
                  isRequired: true,
                  readableName: 'administrative_number',
                  value: 'Not available',
                },
                {
                  checked: true,
                  elementIdentifier: 'issuing_country',
                  enabled: false,
                  id: 'issuing_countrywYJMnQeApGnc',
                  isRequired: true,
                  readableName: 'Issuing Country',
                  value: 'LV',
                },
                {
                  checked: false,
                  elementIdentifier: 'issuing_jurisdiction',
                  enabled: false,
                  id: 'issuing_jurisdictionwYJMnQeApGnc',
                  isRequired: true,
                  readableName: 'issuing_jurisdiction',
                  value: 'Not available',
                },
              ],
              title: 'PID',
              meta: {
                id: 'wYJMnQeApGnc',
                documentIdentifier: 'eu.europa.ec.eudi.pid.1',
                hasExpired: false,
                status: 'Issued',
                isFavorite: true,
                expirationDate: '2025-11-19 00:00',
                issuanceDate: '2025-08-21 00:00',
                issuerDisplay: {
                  name: 'Digital Credentials Issuer',
                  issuingCountry: 'LV',
                  issuingAuthority: 'SIA Dativa',
                  logo: {
                    altText: 'EU Digital Identity Wallet Logo',
                  },
                },
                documentDisplay: {
                  name: 'PID',
                  logo: {
                    altText: 'Personas identifikācijas dati',
                  },
                },
              },
            },
            {
              fields: [
                {
                  checked: true,
                  elementIdentifier: 'family_name',
                  enabled: true,
                  id: 'family_nameDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Family name',
                  value: 'RATHMALSODA HERANISE MIDIANSEHANU',
                },
                {
                  checked: true,
                  elementIdentifier: 'given_name',
                  enabled: true,
                  id: 'given_nameDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Given names',
                  value: 'SANDAMU HASIKA RATHMALGODA',
                },
                {
                  checked: true,
                  elementIdentifier: 'birth_date',
                  enabled: true,
                  id: 'birth_dateDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Date of birth',
                  value: '1965-02-15',
                },
                {
                  checked: true,
                  elementIdentifier: 'issue_date',
                  enabled: true,
                  id: 'issue_dateDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Date of issue',
                  value: '2025-01-29',
                },
                {
                  checked: true,
                  elementIdentifier: 'expiry_date',
                  enabled: true,
                  id: 'expiry_dateDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Date when mDL expires',
                  value: '2025-02-05',
                },
                {
                  checked: true,
                  elementIdentifier: 'age_over_18',
                  enabled: true,
                  id: 'age_over_18Document_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Age attestation: Nearest “true” attestation above request',
                  value: 'true',
                },
                {
                  checked: false,
                  elementIdentifier: 'age_over_21',
                  enabled: false,
                  id: 'age_over_21Document_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'age_over_21',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'age_in_years',
                  enabled: false,
                  id: 'age_in_yearsDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'age_in_years',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'age_birth_year',
                  enabled: false,
                  id: 'age_birth_yearDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'age_birth_year',
                  value: 'Not available',
                },
                {
                  checked: true,
                  elementIdentifier: 'issuing_authority',
                  enabled: true,
                  id: 'issuing_authorityDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Issuing authority',
                  value: 'Test QEAA issuer',
                },
                {
                  checked: true,
                  elementIdentifier: 'document_number',
                  enabled: true,
                  id: 'document_numberDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Licence number',
                  value: 'WE000109',
                },
                {
                  checked: true,
                  elementIdentifier: 'portrait',
                  enabled: true,
                  id: 'portraitDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Portrait of mDL holder',
                  value: '_9jY__Z',
                },
                {
                  checked: true,
                  elementIdentifier: 'driving_privileges',
                  enabled: true,
                  id: 'driving_privilegesDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Categories of vehicles',
                  value:
                    'sign: 10.02\nvalue: \nsign: 25.01\nvalue: \nsign: 03.02bd\nvalue: \nissue_date: 1992-03-01\nexpiry_date: 2026-05-05\nvehicle_category_code: B\nsign: 10.02\nvalue: \nsign: 25.01\nvalue: \nsign: 03.02bd\nvalue: \nissue_date: 2011-04-29\nexpiry_date: 2026-05-05\nvehicle_category_code: BE\nsign: 10.02\nvalue: \nsign: 25.01\nvalue: \nsign: 95\nvalue: . 05.05.2026.\nsign: 03.02bd\nvalue: \nissue_date: 1992-03-01\nexpiry_date: 2026-05-05\nvehicle_category_code: C\nsign: 10.02\nvalue: \nsign: 25.01\nvalue: \nsign: 95\nvalue: . 05.05.2026.\nsign: 03.02bd\nvalue: \nissue_date: 2011-04-29\nexpiry_date: 2026-05-05\nvehicle_category_code: CE\nsign: 10.02\nvalue: \nsign: 25.01\nvalue: \nsign: 95\nvalue: . 05.05.2026.\nsign: 03.02bd\nvalue: \nissue_date: 1992-02-01\nexpiry_date: 2026-05-05\nvehicle_category_code: D\nsign: 10.02\nvalue: \nsign: 25.01\nvalue: \nsign: 95\nvalue: . 05.05.2026.\nsign: 03.02bd\nvalue: \nissue_date: 2011-04-29\nexpiry_date: 2026-05-05\nvehicle_category_code: DE\nsign: 03.02bd\nvalue: \nissue_date: 1985-10-01\nexpiry_date: 2026-05-05\nvehicle_category_code: TROL',
                },
                {
                  checked: true,
                  elementIdentifier: 'un_distinguishing_sign',
                  enabled: true,
                  id: 'un_distinguishing_signDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'UN distinguishing sign',
                  value: 'LV',
                },
                {
                  checked: false,
                  elementIdentifier: 'administrative_number',
                  enabled: false,
                  id: 'administrative_numberDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'administrative_number',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'sex',
                  enabled: false,
                  id: 'sexDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'sex',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'height',
                  enabled: false,
                  id: 'heightDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'height',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'weight',
                  enabled: false,
                  id: 'weightDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'weight',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'eye_colour',
                  enabled: false,
                  id: 'eye_colourDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'eye_colour',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'hair_colour',
                  enabled: false,
                  id: 'hair_colourDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'hair_colour',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'birth_place',
                  enabled: false,
                  id: 'birth_placeDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'birth_place',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_address',
                  enabled: false,
                  id: 'resident_addressDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'resident_address',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'portrait_capture_date',
                  enabled: false,
                  id: 'portrait_capture_dateDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'portrait_capture_date',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'nationality',
                  enabled: false,
                  id: 'nationalityDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'nationality',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_city',
                  enabled: false,
                  id: 'resident_cityDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'resident_city',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_state',
                  enabled: false,
                  id: 'resident_stateDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'resident_state',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_postal_code',
                  enabled: false,
                  id: 'resident_postal_codeDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'resident_postal_code',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_country',
                  enabled: false,
                  id: 'resident_countryDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'resident_country',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'family_name_national_character',
                  enabled: false,
                  id: 'family_name_national_characterDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'family_name_national_character',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'given_name_national_character',
                  enabled: false,
                  id: 'given_name_national_characterDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'given_name_national_character',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'signature_usual_mark',
                  enabled: false,
                  id: 'signature_usual_markDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'signature_usual_mark',
                  value: 'Not available',
                },
              ],
              title: 'mDL',
              meta: {
                id: 'Document_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                type: 'mDL',
                issuanceState: 'Issued',
                hasExpired: false,
                expirationDate: '2025-04-25',
                issuingAuthority: 'Test QEAA issuer',
                issuerCountry: 'LV',
                issuanceDate: '2025-01-29',
              },
            },
          ],
        },
        error: 'string?',
      },
    },
    getRequestDocuments2: {
      request: {
        id: 'string',
        func: 'getRequestDocuments',
        data: null,
      },
      response: {
        id: 'string',
        status: 'SUCCESS',
        data: {
          verifierName: 'EUDI Remote Verifier',
          verifierIsTrusted: true,
          documents: [
            {
              title: 'mDL',
            },
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLfamily_nameDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Family name',
              value: 'Janis',
              checked: true,
              enabled: true,
              elementIdentifier: 'family_name',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLgiven_nameDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Given names',
              value: 'Liepa',
              checked: true,
              enabled: true,
              elementIdentifier: 'given_name',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLbirth_dateDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Date of birth',
              value: '2025-01-27',
              checked: true,
              enabled: true,
              elementIdentifier: 'birth_date',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLissue_dateDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Date of issue',
              value: '2025-01-27',
              checked: true,
              enabled: true,
              elementIdentifier: 'issue_date',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLexpiry_dateDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Date when mDL expires',
              value: '2025-02-03',
              checked: true,
              enabled: true,
              elementIdentifier: 'expiry_date',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLage_over_18Document_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Age attestation: Nearest “true” attestation above request',
              value: 'false',
              checked: true,
              enabled: true,
              elementIdentifier: 'age_over_18',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLage_over_21Document_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'age_over_21',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'age_over_21',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLage_in_yearsDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'age_in_years',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'age_in_years',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLage_birth_yearDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'age_birth_year',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'age_birth_year',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLissuing_authorityDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Issuing authority',
              value: 'Test MDL issuer',
              checked: true,
              enabled: true,
              elementIdentifier: 'issuing_authority',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLdocument_numberDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Licence number',
              value: '4343432',
              checked: true,
              enabled: true,
              elementIdentifier: 'document_number',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLportraitDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Portrait of mDL holder',
              value:
                '9j_4AAQSkZJRgABAQIAJQAlAAD_4QBiRXhpZgAATU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAMAAAITAAMAAAABAAEAAAAAAAAAAAAlAAAAAQAAACUAAAAB_9sAQwADAgICAgIDAgICAwMDAwQGBAQEBAQIBgYFBgkICgoJCAkJCgwPDAoLDgsJCQ0RDQ4PEBAREAoMEhMSEBMPEBAQ_8AACwgBsQFoAQERAP_EAB4AAQABBAMBAQAAAAAAAAAAAAABAgcICQMEBgoF_8QASRAAAQMDAwMCBQAHBAYGCwAAAQACAwQFEQYHEgghMQlBEyJRYXEUIzJCUoGRFWJyshgzOHWCwhZDobHR8CQlJjQ1REaFs8PU_9oACAEBAAA_ANqL_ZSPClERERERERERERERERERERERERERERUv9vypHhSiIiIiIiIi4Q93_k5I_Psvy7_qiw6Vtk961LfaG1W-mbzmqq2pZTwsbj9oveQGjse5IH3Vir16hnRpYq6S31u_thfNE7DjSRVNXFn7SQxPa4fgrqD1J-iR_wCxvxbj_wDa7gP_ANC_E1f6pPRhpaifUUu51VqCpa3Io7RZqt8z_wAOljZEP-J4Vuz60HS04fq9GbnfztND_wD2LyJ9bDa4ainp27M6pdYW5-BXfp8H6U_s0_NT44M7kj_Wu8L8mq9bvTUdZPHQ9Pd1nphK4QSS6jjje6MeHOYKd3B31bycB7OXYqfW30T-kUYpNi72ad7miqfLeImvYD5MYbE4Px93NVwZ_WQ6WYqlsAse4UzBHHI-aC1Uvw2lzWuMeX1IcXMyWO-XBcxxa4tw53vtLeqP0YanjgbNunPY6mVveC6WesiLHfwue2N0Y_Iesk9F670luLYabVWhtTW--WirGYauhnbLE7_ibnv9shejRERERERERERUv9vypHhSiIiIiIijIX5V6vtu07bKq9Xy501voKCB9TU1NRK2KGGJgy973uOGtaO5JIA8Ela5t5vWY0pp7UE9j2W0B_0opaaV0ZutxqX00VRxdjMUQHMtJ_ZLi0keWrEDfD1N-pzeCpMNs1M3RVoc3j-gWF5j5fd8zsyH-RasbNS7n7k6ypP7P1buHqS90jZPitguN1nqYw-INkcRnv5XmCSexPhEySMEnAQEjwSnJx8uP8AVTyd_Ef6pyd3-Y9_Pfyge8Yw89vHfwo5O-pVydpuoPenZKsM-1m4d3sTXSfEkpoJS6CQ_V0Tg5hP5C2JdNnrERzPp9MdS1mFO48YxqK0U5c0Euxymp25-UDuXMz_AIXLZbpTWGntb2Ci1TpC_Ul5s9yiZNSV1FM2aCVjs9w9p748HuDkY_aBC_fyFKIiIiIiIiKl_t-VI8KURERERRkfVdK43KitlHLcLhcKekpIGfFlmnlDGMZ_E5xIDR9z2WIPUJ6oPTxs02W1aSvTNf6gAcBTWWpa-lheOwEtSAYwM-zC4_XitPu8PUzvPvdqC63vWuvr1LT3Ob4ptcddIyiiZz5RxthDuBDfqRlWlyfGShJPknsiIiIiIiZP1VTXuJ7uJ8nz9fKvv0zdXe7_AEwaghuGjL1UVFikmDq6xVUhdSVLB-3huPkecftNwR75W7jpv6v9nOp2xCs0BqNkd7hjY64WKsIiraJ3FvLLCf1rORAD4-QPIAlrsht9GOLhnPnwqh4UoiIiIiIipf7flSPClERERFB8K12_m_m33Ttt_Xbg7hXcU9NSjFNSxvBqK6Y_sxRM8kl2AfZoBJ-UFaZOsT1B9fdVdJT6Uo7QNK6UpZnSuoYKovfWOPYGd_ytOG_ugYysRnPz4Kjk7OeRz9cqEREREREREU83YI5HBxkZ8r9vSurNS6HvtLqXSN7rbNdaJwkgq6SZ0U0Z98EHJB75Hus_Omz1dtyNJV9Hp7qApRqqxktjddKSJkdxp2-73BoDJh3OR8rhjsVte2z3R0JvFouh17ttqilvlkr2coqmne5pYWn5mPY4B0cjT-0x7Q4HsQAvYZb9VUiIiIiIipf7flSPClERERF4vdXdLR-zWgLzuVr28C32ayUxnne7HKR2QGRRtP7Ukji1jWeSXADHcrQj1k9WN16rtxo9WSWR1ms1ugNLbaAzukw3k4mR_fjzcCMhoAGBhY85I8EoiIiIiIiIiIiZOMZU8nYI5HBOSMq-nS71abldK-sf7b0VXGostdLH_a1kmcTTVjB5IHlkgGeLx3GRnK3v9P3UJt51Jbe0e4e3V1E8M2I62ieQKi3VAALoZmeWuwcg-HN4ubkOBN0g5rhkFVIiIiIiKl_t-VI8KURERF1pKhkeXukwG-SQcAfnOMDySfZaS_U96vnb27iO2m0TdXS6K0hUPY-SneTDX1wy18vbs5rAXNaT7lx-iwU5HOcnP1RERERERERERERE5H6lXn6Yep3X_S3uFHrjRtQailnaIbpapXEQ3CnySQ7HhwJPF3kZOFvq6c-oHRPUttbQboaFndHT1DjTV1HKQZrfWMDTJBJjsDhzHA-C17XeCALroiIiIiKl_t-VI8KURERFrd9UPreOgbTV9O21l1lh1LdIf_aC4U7-JoqRzDmna7yJXjHI-zPl8uHHT2ZHZJ8E-VSiIiIiIiIiIiIiIp5OHhx_qspegrq6uvSzueyS4zSz6K1G-OmvlKCeMBzgVTR_EweR7sJ_hC36W250d2oKa522qZU0tZEyeGVjgQ-N4Ba4Y7EEEH-a7yIiIiIqX-35UjwpRERF1KqshoKeWsq52xQQsdJJI92A1gBJJz2wACST9F81fUHraPcXfLXWuKOsdWU13vlZUU0_f9ZAJSI3j6Dg1uPsrbIiIiIiIiIiIiIiIiqD3e3t2W5n0jepiu3J23r9kNVVj57toWJklrnleC6W2PPFsZ9_1TsN_wALox4C2GoiIiIipf7flSPClEREWIXqi7nXvbDpJv79P1bqWr1VXU2nDO1-HMhna90wb75dFDI37CRx8gLQq4nx7fRQiIiIiIiIiIiIiIiIskugzqEh6dOoexasulVwsN2YbPeXPGGx00zwBIT7CNwZJgecFfQZSVcVZBHVU0okgmjbJG9juTS0jIcD75BBXaRERERUv9vypHhSiIiLU960u7sNZdNE7JUTnl1vEl-uAz8vKRpjhbjxkN59_wC-tXCIiIiIiIiIiIiIiIiKQ5w8OI9_K3--nJv1Qb5dNFha74kd60bHFpy6xySc3ySQwsMdQCe_GVhae_hwkb4asqkREREVL_b8qR4UoiIi0ber-T_pcTDPjT9v_wArlhAiIiIiIiIiIiIiIiIiLZF6K2sqm3bua60BLWsbRXqwxXFkLnY-JPTzhgLR9fhzSE_YLcKCD4KlERERUv8Ab8qR4UoiIi0besAT_pczdv8A6ft_-VywgRERERERERERERERERFkF0Kbnt2m6p9Bamq68UlBUXFtrrpSwvAgqmmEjiO-fmAz7eV9EDMeGuOCBj8fUELmREREVL_b8qR4UoiIi0besAR_pcz-f_gFv_yuWECIiIiIiIiIiIiIiIiIuSnnnp5o56eZ8UsTg-N7HFrmuB7EEeCPqvpd6fNbU24uymiNb0tQ6Vl4sVJUF7hhxcY2h-e5-bkDkexJHsrjoiIiKl_t-VI8KURERaNvV_8A9rmb_cFD_lcsIERERERERERERERERERS3yt43pBatOoekdljfE9h0xqS4Wscz2c14jqwQP3R_wClHt9QSs4URERFS_2_KkeFKIiItG_rAf7XE3-4Lf8A5XLB9EREREREREREREREREUt8ra56I2pbu-3bqaPkqy61001rucFO5o4x1ErZ45XNI8l7IYgQfHwxj95bS0RERFS_wBvypHhSiIiLRt6wP8Atcz_AO4Lf_lcsIERERERERERERERERERFnr6P-5dZo_qRr9BTOlFHrWzTQFpIDG1FMfixyHIySGiZgwcD4hJBwt17Hl2Sexb7LkRERFS_',
              checked: true,
              enabled: true,
              elementIdentifier: 'portrait',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLdriving_privilegesDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Categories of vehicles',
              value: 'issue_date: 27 Jan 2025\nexpiry_date: 27 Jan 2025\nvehicle_category_code: AM',
              checked: true,
              enabled: true,
              elementIdentifier: 'driving_privileges',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLun_distinguishing_signDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'UN distinguishing sign',
              value: 'FC',
              checked: true,
              enabled: true,
              elementIdentifier: 'un_distinguishing_sign',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLadministrative_numberDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'administrative_number',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'administrative_number',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLsexDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'sex',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'sex',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLheightDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'height',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'height',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLweightDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'weight',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'weight',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLeye_colourDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'eye_colour',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'eye_colour',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLhair_colourDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'hair_colour',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'hair_colour',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLbirth_placeDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'birth_place',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'birth_place',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLresident_addressDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'resident_address',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'resident_address',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLportrait_capture_dateDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'portrait_capture_date',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'portrait_capture_date',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLnationalityDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'nationality',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'nationality',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLresident_cityDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'resident_city',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'resident_city',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLresident_stateDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'resident_state',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'resident_state',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLresident_postal_codeDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'resident_postal_code',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'resident_postal_code',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLresident_countryDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'resident_country',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'resident_country',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLfamily_name_national_characterDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'family_name_national_character',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'family_name_national_character',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLgiven_name_national_characterDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'given_name_national_character',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'given_name_national_character',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLsignature_usual_markDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'signature_usual_mark',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'signature_usual_mark',
            },
            {},
          ],
        },
        error: 'string?',
      },
    },
    getTransactions: {
      request: {
        id: 'string',
        func: 'getTransactions',
        data: {
          documentId: 'string',
        },
      },
      response: {
        id: 'string',
        status: 'success|error',
        data: {
          transactions: [
            {
              documentIdentifier: 'eu.europa.ec.eudi.pid.1',
              documentId: 'Document_EudiWalletDocumentManager_6800ceac-ddbe-4fb3-88bb-37c23e5e2b76',
              eventType: 'DOCUMENT_PRESENTED',
              id: 'ef1c8b5e-9b9a-41b5-837e-2d517fe0f96a',
              documentDisplay: { name: 'PID' },
              status: 'SUCCESS',
              timestamp: 1737987746164,
            },
            {
              documentIdentifier: 'mDL',
              documentId: 'Document_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              eventType: 'DOCUMENT_ISSUED',
              id: 'ea4bd5fd-b74e-45a5-a443-020311912cd8',
              documentDisplay: { name: null },
              status: 'SUCCESS',
              timestamp: 1737987746174,
            },
            {
              documentIdentifier: 'mDL',
              documentId: 'Document_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              eventType: 'DOCUMENT_DELETED',
              id: 'ea4bd5fd-b74e-45a5-a443-020311912cd82',
              documentDisplay: { name: null },
              status: 'ERROR',
              timestamp: 1737987746174,
            },
            {
              documentIdentifier: 'eSign',
              documentId: 'Document_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              eventType: 'DOCUMENT_SIGNED',
              id: 'ea4bd5fd-b74e-45a5-a443-020311912cd822',
              documentDisplay: { name: null },
              status: 'CANCELLED',
              timestamp: 1737987746174,
              authority: 'LVRTC',
            },
            {
              documentIdentifier: 'mDL',
              documentId:
                'Document_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f61',
              eventType: 'test',
              id: 'ea4bd5fd-b74e-45a5-a443-020311912cd823',
              documentDisplay: { name: null },
              status: 'ERROR',
              timestamp: 1737987746174,
              authority: 'Test issuer',
            },
          ],
        },
      },
    },
    resolveDocumentOffer: {
      response: {
        id: 'string',
        status: 'SUCCESS',
        data: {
          documents: [
            {
              title: 'mDL',
            },
            {
              title: 'PID',
            },
          ],
          issuerName: 'edim-demo-issuer-dev.zzdats.lv',
          txCodeLength: 5,
        },
      },
    },
    getOfferCodeData: {
      response: {
        id: 'string',
        status: 'SUCCESS',
        data: {
          issuerName: 'edim-demo-issuer-dev.zzdats.lv',
          txCodeLength: 5,
          offerUri:
            'openid-credential-offer://credential_offer?credential_offer\u003d%7B%22credential_issuer%22:%20%22https://edim-demo-issuer-dev.zzdats.lv%22%2C%20%22credential_configuration_ids%22:%20%5B%22eu.europa.ec.eudi.mdl_mdoc%22%2C%20%22eu.europa.ec.eudi.pid_mdoc%22%5D%2C%20%22grants%22:%20%7B%22urn:ietf:params:oauth:grant-type:pre-authorized_code%22:%20%7B%22pre-authorized_code%22:%20%2283d7bac2-c1c9-45b9-8b77-c1d7b14334b3%22%2C%20%22tx_code%22:%20%7B%22length%22:%205%2C%20%22input_mode%22:%20%22numeric%22%2C%20%22description%22:%20%22Please%20provide%20the%20one-time%20code.%22%7D%7D%7D%7D',
        },
      },
    },
    getUserSignOptions: {
      request: {
        id: 'string',
        func: 'getUserSignatureOptions',
        data: null,
      },
      response: {
        id: 'string',
        status: 'SUCCESS',
        data: {
          options: {
            eSign: [
              {
                id: 'string',
                name: 'E-Sign',
                expiresOn: '2028-03-05T11:49:10',
                issuedOn: '2025-03-05T11:49:10',
                type: 'eSign',
              },
              {
                id: 'string1',
                name: 'E-Sign',
                expiresOn: '2028-03-05T11:49:10',
                issuedOn: '2025-03-05T11:49:10',
                type: 'eSign',
              },
            ],
            eSeal: [
              {
                id: 'string',
                name: 'E-Seal',
                expiresOn: '2028-03-05T11:49:10',
                issuedOn: '2025-03-05T11:49:10',
                type: 'eSeal',
              },
            ],
          },
        },
      },
    },
    pickFiles: {
      request: {
        id: 'string',
        func: 'pickFiles',
        data: {},
      },
      response: {
        id: 'string',
        status: 'success|error',
        data: {
          files: [
            {
              path: '/path/to/file.pdf', // e.g. "/path/to/file.pdf"
              name: 'file.pdf', // e.g. "file.pdf"
              size: '888', // in bytes
              type: '.pdf', // e.g .pdf, .docx
              isContainer: true, // e.g .edoc, .asice
              isValid: true, // invalid if file over 25 MB
              allowedOutputFormats: ['.pdf', '.edoc'],
              containerInfo: {
                // if isContainer is true
                signers: [
                  {
                    name: 'Test Testiņš',
                    signedAt: '2025-03-07T09:58:13Z',
                    type: 'eSign', // eSign, eSeal, testESign
                  },
                  {
                    name: 'Māra Paraudziņa',
                    signedAt: '2025-03-07T09:58:13Z',
                    type: 'eSeal', // eSign, eSeal, testESign
                  },
                  {
                    name: 'Māris Paraudziņš',
                    signedAt: '2025-03-07T09:58:13Z',
                    type: 'testESign', // eSign, eSeal, testESign
                  },
                ],
                files: [
                  {
                    name: 'file.docx',
                  },
                  {
                    name: 'test.pptx',
                  },
                ],
              },
            },
          ],
        },
      },
    },
    getSigningMethods: {
      request: {
        id: 'string',
        func: 'getSigningMethods',
        data: null,
      },
      response: {
        id: 'string',
        status: 'success|error',
        data: {
          // Same data as in getUserSignOptions, tbd
          methods: [
            {
              meta: {
                id: 'Document_EudiWalletDocumentManager_a67bd590-b31d-4348-b60e-54b31e5da796',
                documentIdentifier: 'eSign',
                issuerDisplay: {
                  issuingAuthority: '',
                  issuerCountry: '',
                },
                documentDisplay: {
                  backgroundColor: null,
                  textColor: null,
                  description1: null,
                  description2: null,
                  description3: null,
                  name: null,
                },
                issuanceState: 'Issued',
                hasExpired: false,
                isFavorite: true,
                expirationDate: '2025-11-04T12:05:52+01:00',
                issuanceDate: '2024-11-04T12:05:52+01:00',
                displayNumber: '545353543', // todo
              },
            },
            {
              meta: {
                id: 'Document_EudiWalletDocumentManager_a67bd590-b31d-4348-b60e-54b31e5da755',
                documentIdentifier: 'eSeal',
                issuerDisplay: {
                  issuingAuthority: '',
                  issuerCountry: '',
                },
                documentDisplay: {
                  backgroundColor: null,
                  textColor: null,
                  description1: null,
                  description2: null,
                  description3: null,
                  name: null,
                },
                issuanceState: 'Issued',
                hasExpired: false,
                isFavorite: true,
                expirationDate: '2025-11-04T12:05:52+01:00',
                issuanceDate: '2024-11-04T12:05:52+01:00',
                displayNumber: '545353543', // todo
              },
            },
          ],
        },
      },
    },
    getState: {
      request: {
        id: 'string',
        func: 'getState',
        data: null,
      },
      response: {
        id: 'string',
        status: 'SUCCESS',
        data: {
          theme: 'string', // light | dark | system
          language: 'en', // en | lv
          fullName: 'Test Testiņš',
          system: 'ios', // android | ios
          env: 'dev', // prod | dev
          appVersion: '1.0.0',
          updateAvailable: false,
          scaleFactor: 1.0,
          reduceMotion: false,
          ios: {
            reduceTransparency: false,
          },
        },
      },
    },
    getBiometricAvailability: {
      request: {
        id: 'string',
        func: 'getBiometricAvailability',
        data: {},
      },
      response: {
        id: 'string',
        status: 'SUCCESS',
        data: {
          type: 'android', // "touchId", "faceId", "android", "exists", null
        },
      },
    },
  }),
  getters: {
    getDocumentDetailsGetter: (state) => (id) =>
      state.getDocumentDetails?.response?.find((item) => item.data.meta.id === id),
  },
  actions: {
    deleteDocument(params) {
      this.getDocuments.response.data.documents = this.getDocuments.response.data.documents.filter(
        (item) => item.meta.id !== params
      );
    },
  },
});
